Ruby on Rails capstone project - Budget app
mryeminthu/budget-app pull request #4
Opened 2024-01-19 14:59 UTC by mryeminthu

- Build a webapp that requires the user to log in.
- Use devise gem for authentication.
- Limit access to webapp resources based on authorization rules.
- Create Home page (categories page)
- Create Transactions page
- Create "Add a new category" page
- Create "Add a new transaction" page

2024-01-19 17:10 UTC, Gambit142 requested changes
Hi @mryeminthu 👋, 

Good job so far!

## Highlights
- Setup linters correctly ✔️ 
- Created controllers ✔️ 
- Created models ✔️ 
- Created routes ✔️ 
- All tests passed ✔️ 

You still need to work on some issues to go to the next project, but you are almost there!

## Required Changes ♻️
_Kindly check the comments under the review._

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend considering them as they can improve your code._

You can also consider the following:

N/A

Cheers, and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.

#### Please tag me in your question so I can receive the notification. You can tag me by typing @Gambit142

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think the code review was unfair, request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._
```

2024-01-19 17:10 UTC, Gambit142 commented on app/views/expenses/new.html.erb
> +<% end %>
- [ ] There is a little bug in your application that I would like to bring to your attention. If I have two categories (let's say Sports and Fashion) created, and I try to create a new transaction for **_The Fashion_** category but I entered through the **_Sports section_**, the transaction is created for the **_Sports section_** instead of the _**Fashion**_ category.

---
Although the form allows me to choose the Fashion category, it will be created for the Sports category instead. This can bring about unexpected behaviours in your application. I would advise you to rectify it and ensure that the transaction is recorded for the correct category chosen in the form. 💻 😎 

---
You can watch this [video](https://www.loom.com/share/c8b91d1f7e9b463798c06064a464bda5) to better understand the change required here 📹

2024-01-19 17:10 UTC, Gambit142 commented on spec/models/category_spec.rb
> +end
- [ ] Great work writing model tests for your application. However, one of the requirements is to also write integration tests for the major components of the application. Kindly write these tests as the give a level of credibility that your application works correctly. 👍 💻

2024-01-20 00:52 UTC, mryeminthu commented on spec/models/category_spec.rb
> +end
Dear @Gambit142. Please let me know about major components of the application.

2024-01-20 08:45 UTC, OyePriscilla requested changes
Hi @mryeminthu 👍 , 

Great work on making the changes requested by a previous reviewer 👏 
You've done well implementing some of the requested changes, but there are still some which aren't addressed yet.

![so-close-so-close-seth-meyers](https://user-images.githubusercontent.com/103386183/196425724-8ca5825c-b02a-4983-b976-4bd0a2f70f9a.gif)

 ## Highlights
Items in the app categorized correctly ✔️ 

 ## Required Changes ♻️
_Check the comments under the review._

## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._


Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**


------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2024-01-20 08:45 UTC, OyePriscilla commented on spec/controllers/categories_controller_spec.rb
> +  end
- [ ] Great adding more test to make your app more robust, but please as stated earlier; you are to **add integration tests**. In RSpec, integration tests typically refer to tests that involve multiple parts of the system working together, such as testing the interaction between controllers, models, and views. 
Commonly, integration tests are written using tools like Capybara to simulate user interactions with the application. Integration tests often involve navigating through the application, interacting with forms, and making assertions based on the resulting page content.

2024-01-20 13:17 UTC, Gambit142 requested changes
Hi @mryeminthu 👋, 

Great work on making the changes requested by a previous reviewer 👏 

## Highlights
- Setup linters correctly ✔️ 
- Created controllers ✔️ 
- Created models ✔️ 
- Created routes ✔️ 
- All tests passed ✔️ 

You've done well implementing some of the requested changes, but there are still some which aren't addressed yet.

 ## Required Changes ♻️
_Kindly check the comments under the review._

## Optional suggestions

N/A

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you consider them as they can improve your code. Some of them were simply missed by the previous reviewer and addressing them will improve your application._


Cheers, and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.

#### Please tag me in your question so I can receive the notification. You can tag me by typing @Gambit142

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**


------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think the code review was unfair, request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2024-01-20 13:17 UTC, Gambit142 commented on spec/features/category_spec.rb
> +end
- [ ] Great work writing feature tests for the `Categories` component. As highlighted in the project requirements, you ought to write unit and integration tests for the major components of your application. Kindly write _**integration/feature**_ tests for the `Expenses` component that you created. The _**integration/feature**_ ensures that users' interactions with the application behave as expected. Kindly implement this change. 👍 💻

#### Project requirement

![image](https://github.com/mryeminthu/budget-app/assets/77106962/9dc668df-159f-4408-b948-4964d7b18297)

2024-01-20 13:53 UTC, gemmen29 approved these changes
Hi @mryeminthu, 

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 

## Highlights 💯 
- No linters errors ✔️ 
- Descriptive pull request ✔️ 
- Descriptive commit messages ✔️ 

![](https://media.giphy.com/media/mCIjCgs3nWQWfJZvPA/giphy-downsized-large.gif)

## Optional suggestions

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2024-01-20 13:57 UTC, merged